### ISSUE TITLE
Calculation of s_test

### ISSUE THREAD

**Issue by vidit98** [dragonlzm/ISAL#4]
I had doubt in the calculation of s_test in line number 55 of [utils.py ](https://github.com/dragonlzm/ISAL/blob/669e7212070865a820e950162df9f1a70d2d7950/classification/src/utils.py#L55)inside classification/src. I see it is different from the description given in the paper Algorithm 3. I see there is no damping factor or scaling factor in algorithm 3 whereas they are present in the code. Could you please tell me how to interpret these terms?

**Comment by dragonlzm** [comment]
When we implement the calculation of the s_test, we actually follow the LiSSA algorithm for the second-order approximation, please refer to https://arxiv.org/pdf/1602.03943.pdf for more information. Since we just draw one sample to calculate the second-order approximation in each iteration, it is more suitable for us to use a smaller update ratio(something like what we commonly do in the SGD). Hope this short explanation can address your doubt.
